# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run stock check

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    # You can use configuration variables with the `vars` context for dynamic jobs
    if: ${{ vars.USE_VARIABLES == 'true' }}
    runs-on: ${{ vars.RUNNER }}
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
      env:
        REPOSITORY_VAR: ${{ vars.TWILIO_ACCOUNT_SID }}

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm start
        env:
          TWILIO_ACCOUNT_SID: ${{ vars.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ vars.TWILIO_AUTH_TOKEN }}
          MY_SMS: ${{ vars.MY_SMS }}
          TWILIO_SMS: ${{ vars.TWILIO_SMS }}
